### ISSUE TITLE
⚡ Release v0.0.0

### ISSUE THREAD

**Issue by in4s** [in4s/bem-tags#7]
- [x] ** Update RSR (optional)
- [ ] ** if the branch 0.0 does not exist
    - [ ] git checkout PREVIEWS_BRANCH_NAME
    - [ ] git pull
    - [ ] create the branch 0.0
    - [ ] git checkout the branch 0.0
    - [ ] git push
    - [ ] !!! If the branch has the highest number, set it as the default branch on [Github](https://github.com/in4s/bem-tags/settings/branches)
- [ ] git checkout the branch 0.0
- [x] git pull
- [x] git checkout -b Release_v0.0.0_#7
- [x] Fix the current version number in files:
    - [x] In README.md
    - [ ] In composer.json
- [x] git add . , git commit -m "⚡ Release v0.0.0 close #7"
- [ ] (C*rmr) By process IV Create pull request "⚡ Release v0.0.0 close #7"
------
- [ ] !!!!!!!!!!!!!!!!!!!!!! (cRM*R) Review pull request, Merge it, !!!!!!!!!!!!!! swapping title and description, Remove remote branch
- [ ] click and save https://github.com/in4s/bem-tags/releases/new?tag=v0.0.0&target=0.0
- [ ] Increase the version number in local data.js
- [ ] Remove local branch
- [ ] click and save https://github.com/in4s/bem-tags/issues/new/?assignees=in4s&labels=test,canProceed,Urgent&title=☑+v0.0.0+on+m&body=-+%5B+%5D+Pin+this+issue%3B+Pin+it+to+the+left%0D%0A-+%5B+%5D+Run+the+test+and+complete+it%0D%0A-+%5B+%5D+Unpin+this+issue+after+closing+it
- [ ] Pin this test issue; Pin it to the left
- [ ] Close milestone with current version name
- [ ] Unpin this issue
